// src/sw.ts
// Service worker source — compiled to public/sw.js by Serwist at build time.
//
// WHY /// <reference lib="webworker" />:
// TypeScript does not include service worker types by default.
// This directive tells TypeScript to load the WebWorker type definitions,
// which includes ServiceWorkerGlobalScope. Without it, TypeScript cannot
// find the ServiceWorkerGlobalScope type and throws ts(2552).
/// <reference lib="webworker" />

import { defaultCache } from "@serwist/next/worker";
import type { PrecacheEntry, SerwistGlobalConfig } from "serwist";
// WHY CacheFirst / NetworkFirst are imported as classes, not strings:
// Serwist expects actual strategy instances, not string names.
// Writing handler: "CacheFirst" passes a string, which is type 'string'
// not type 'RouteHandler' — hence the ts(2322) error.
import { Serwist, CacheFirst, NetworkFirst } from "serwist";

// Extend the service worker global scope to include Serwist's injected manifest.
// __SW_MANIFEST is injected at build time by @serwist/next — do not remove.
declare global {
  interface ServiceWorkerGlobalScope extends SerwistGlobalConfig {
    __SW_MANIFEST: (PrecacheEntry | string)[] | undefined;
  }
}

// Cast self to the service worker global scope so TypeScript resolves correctly.
declare const self: ServiceWorkerGlobalScope;

const serwist = new Serwist({
  // Precache all pages and static assets generated by Next.js
  precacheEntries: self.__SW_MANIFEST,

  // Activate new service worker immediately — no waiting for old SW to unload
  skipWaiting: true,
  clientsClaim: true,

  navigationPreload: true,

  runtimeCaching: [
    // Google Fonts — serve from cache, fall back to network
    // CacheFirst = fast load after first visit; fonts rarely change
    {
      matcher: /^https:\/\/fonts\.(googleapis|gstatic)\.com/,
      handler: new CacheFirst({
        cacheName: "google-fonts",
      }),
    },

    // Session API — network first with cache fallback
    // NetworkFirst = always try server; use cache only when offline
    // This ensures answers are always fresh when online
    {
      matcher: /\/api\/sessions\/[^/]+$/,
      handler: new NetworkFirst({
        cacheName: "session-api",
        networkTimeoutSeconds: 5,
      }),
    },

    // All other routes use Next.js recommended defaults
    ...defaultCache,
  ],
});

serwist.addEventListeners();
